files:
  network/LAN:
    mode: 0666
    read_cmd: "nmcli -g IP4.ADDRESS device show enp0s3"
    write_cmd: >
      nmcli device modify enp0s3
      ipv4.method manual
      ipv4.addresses "{value}/24"
      ipv4.gateway "10.0.2.2"
      ipv4.dns "10.180.8.13,10.180.8.12"
    process_output: | # 处理获取的ip地址，移除子网掩码部分 按照'/'分割字符串，取第一个元素
      if '/' in output:
          output = output.split('/')[0]  
    default_value: "0.0.0.0"

  service/timezone:
    mode: 0666
    read_cmd: "timedatectl | grep 'Time zone' | awk -F': ' '{print $2}'"
    write_cmd: "timedatectl set-timezone {value}"
    default_value: "Unknown"
  time/uptime:
    mode: 0444
    read_cmd: "uptime -p"
    default_value: "Unknown"
  time/curtime:
    mode: 0444
    read_cmd: "date +'%Y-%m-%d %H:%M:%S'"
    default_value: "Unknown"
  time/timezone:
    mode: 0666
    read_cmd: "timedatectl | grep 'Time zone' | awk -F': ' '{print $2}'"
    write_cmd: "timedatectl set-timezone {value}"
    default_value: "Unknown"
  NTP/enable:
    mode: 0666
    read_cmd: "systemctl is-active ntp"
    write_cmd: "if [ {value} -eq 1 ]; then systemctl enable --now ntp; else systemctl disable --now ntp; fi"
    process_output: |
      if output.strip() == "active":
          output = '1' 
      else:
          output = '0'
    default_value: '0'
  NTP/server:
    mode: 0666
    read_cmd: "grep '^server' /etc/ntp.conf | awk '{print $2}'"
    write_cmd: |
      #1. stop ntp server
      systemctl stop ntp
      #2. remove existing server
      sed -i '/^server/d' /etc/ntp.conf
      #3. add new ntp server
      for server in $(echo {value}); do
        echo "server $server iburst" >> /etc/ntp.conf
      done
      #4. start ntp server
      systemctl restart ntp
    default_value: "ntp1.aliyun.com ntp2.aliyun.com" 

  
  #system/hostname:
  #  mode: 0666
  #  read_cmd: "hostname"
  #  write_cmd: "hostnamectl set-hostname {value}"
  #  default_value: "Unknown"
